version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: 
      context: ./etl
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/data
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db

  jupyterlab:
    image: jupyter/scipy-notebook
    volumes:
      - ./data:/home/jovyan/work/data
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: start.sh jupyter lab --ip=0.0.0.0 --port=8888 --no-browser
    depends_on:
      - db

volumes:
  pgdata:
